EventSystem/Models/StatisticViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EventSystem.Models
{
    public class StatisticViewModel
    {
        [Display(Name = "عدد الحضور في الفعالية")]
        public int CountAll { get; set; }

        [Display(Name = "عدد الإناث")]
        public int CountFemale { get; set; }

        [Display(Name = "عدد الذكور")]
        public int CountMale { get; set; }

        [Display(Name = "عدد الطلاب")]
        public int CountStudent { get; set; }

        [Display(Name = "عدد الموظفين")]
        public int CountEmployee { get; set; }

        [Display(Name = "عدد الزائرين")]
        public int CountVisitor { get; set; }

        [Display(Name = "عدد أعضاء هيئة التدريس ")]
        public int CountStaff { get; set; }

        [Display(Name = "عدد الزائرين أقل من 18 سنه")]
        public int CountUnder18 { get; set; }

        [Display(Name = "عدد الزائرين  من 18 - 30 سنه")]
        public int Count18TO30 { get; set; }

        [Display(Name = "عدد الزائرين أكبر من 30 سنه")]
        public int CountAbove30 { get; set; }

        public Models.Event Event { get; set; }
        //public int EventId { get; set; }
    }

    public class MainViewModel
    {
        public StatisticViewModel statisticViewModel { get; set; }

        public List<Event> events { get; set; }
    }
}

EventSystem/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EventSystem.Models;

namespace EventSystem.Controllers
{
    [Authorize]
    public class StatisticsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: StatisticViewModels
        public ActionResult Index(int? id)
        {
            //the last one is for how the dropdawnlist well choese by defult
            MainViewModel mainViewModel;
            StatisticViewModel statisticView;
            var data = db.Events.ToList();

            if (id == null)
            {
                ViewBag.EventId = new SelectList(db.Events, "EventID", "Name");

                statisticView = new StatisticViewModel
                {
                    //All visitors from All Event "NO ID"
                    Event = null,
                    CountAll = db.Visitors.Count(),
                    CountMale = db.Visitors.Where(a => a.Gender == "ذكر").Count(),
                    CountFemale = db.Visitors.Where(a => a.Gender == "أنثى").Count(),
                    CountEmployee = db.Visitors.Where(a => a.Type == "موظف").Count(),
                    CountStudent = db.Visitors.Where(a => a.Type == "طالب").Count(),
                    CountStaff = db.Visitors.Where(a => a.Type == "	عضو هيئة التدريس").Count(),
                    CountVisitor = db.Visitors.Where(a => a.Type == "زائر").Count(),
                    CountUnder18 = db.Visitors.Where(a => a.Age < 18).Count(),
                    Count18TO30 = db.Visitors.Where(a => a.Age >= 18 && a.Age <= 30).Count(),
                    CountAbove30 = db.Visitors.Where(a => a.Age > 30).Count(),

                };

                mainViewModel = new MainViewModel()
                {
                    statisticViewModel = statisticView,
                    events = data
                };
            }
            else
            {

                ViewBag.EventId = new SelectList(db.Events, "EventID", "Name", id);

                var eventModel = db.Events.Find(id);
                if (eventModel == null)
                {
                    return HttpNotFound();
                }
                statisticView = new StatisticViewModel
                {
                    Event = eventModel,
                    CountAll = eventModel.Visitors.Count(),
                    CountMale = eventModel.Visitors.Where(a => a.Gender == "ذكر").Count(),
                    CountFemale = eventModel.Visitors.Where(a => a.Gender == "أنثى").Count(),
                    CountEmployee = eventModel.Visitors.Where(a => a.Type == "موظف").Count(),
                    CountStudent = eventModel.Visitors.Where(a => a.Type == "طالب").Count(),
                    CountStaff = eventModel.Visitors.Where(a => a.Type == "	عضو هيئة التدريس").Count(),
                    CountVisitor = eventModel.Visitors.Where(a => a.Type == "زائر").Count(),
                    CountUnder18 = eventModel.Visitors.Where(a => a.Age < 18).Count(),
                    Count18TO30 = eventModel.Visitors.Where(a => a.Age >= 18 && a.Age <= 30).Count(),
                    CountAbove30 = eventModel.Visitors.Where(a => a.Age > 30).Count(),

                };

            }

            mainViewModel = new MainViewModel()
            {
                statisticViewModel = statisticView,
                events = data
            };
            return View(mainViewModel);
        }
    }
}

EventSystem/Views/Statistics/EventDetail.cshtml
@{
    ViewBag.Title = "تفاصيل الفعالية";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EventDetail</h2>

EventSystem/Views/Statistics/Index.cshtml
@model EventSystem.Models.MainViewModel

@{
    /**/

    ViewBag.Title = "الاحصائيات";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*@Model.CountAll
    @Model.CountMale
    @Model.CountFemale
    @Model.CountStudent
    @Model.CountEmployee
    @Model.CountStaff
    @Model.CountVisitor
    @Model.CountUnder18
    @Model.Count18TO30
    @Model.CountAbove30*@

<h2>الاحصائيات</h2>

@using (Html.BeginForm("Index", "Statistics", FormMethod.Get, new { @id = "form-event", @name = "myForm" }))
{
    <div class=" col-md-12">
        <div class=" col-md-2">
            <label class="form-control">اسم الفعالية </label>
        </div>
        <div class=" col-md-4">
            @Html.DropDownList("EventId", null, "جميع الفعاليات", new { @class = "form-control " })
        </div>
        <div class=" col-md-2">
            <label class="form-control">عدد الزوار </label>
        </div>
        <div class=" col-md-4">
            <label class="form-control">@Model.statisticViewModel.CountAll زائر </label>
        </div>
    </div>
}
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>

<script>
    $("#EventId").on('change', function () {
        var getValue = $(this).val();
        var frm = document.getElementById('form-event') || null;
        if (frm) {
            frm.action = '../../Statistics/Index/' + getValue;
        }
        document.myForm.submit();
    });
</script>

@*<canvas id="myChart"></canvas>*@
<div class="col-md-4">
    <canvas id="ChartSex"></canvas>
</div>
<div class="col-md-4">

    <canvas id="ChartAge"></canvas>
</div>
<div class="col-md-4">

    <canvas id="ChartType"></canvas>
</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

<script>
    var ctx = document.getElementById('ChartSex').getContext('2d');
    var chart = new Chart(ctx, {
        type: 'doughnut',
        data: {
            labels: [
                '@Html.DisplayNameFor(model => model.statisticViewModel.CountMale)',
                '@Html.DisplayNameFor(model => model.statisticViewModel.CountFemale)',
            ],
            datasets: [{
                label: 'إحصائيات',
                backgroundColor: [
                    "rgba(255, 99, 132, 0.2)",
                    "rgba(255, 159, 64, 0.2)",
                ],
                borderWidth: 2,
                data: [
                    @Model.statisticViewModel.CountMale,
                    @Model.statisticViewModel.CountFemale,
                    ]
            }]
        },
    });
</script>
<script>
    var ctx = document.getElementById('ChartAge').getContext('2d');
    var chart = new Chart(ctx, {
        type: 'doughnut',
        data: {
            labels: [
                '@Html.DisplayNameFor(model => model.statisticViewModel.CountUnder18)',
                '@Html.DisplayNameFor(model => model.statisticViewModel.Count18TO30)',
                '@Html.DisplayNameFor(model => model.statisticViewModel.CountAbove30)',
            ],
            datasets: [{
                label: 'إحصائيات',
                backgroundColor: [
                    "rgba(255, 99, 132, 0.2)",
                    "rgba(255, 159, 64, 0.2)",
                ],
                borderWidth: 2,
                data: [
                    @Model.statisticViewModel.CountUnder18,
                    @Model.statisticViewModel.Count18TO30,
                    @Model.statisticViewModel.CountAbove30,
                    ]
            }]
        },
    });
</script>
<script>
    var ctx = document.getElementById('ChartType').getContext('2d');
    var chart = new Chart(ctx, {
        type: 'doughnut',
        data: {
            labels: [
                '@Html.DisplayNameFor(model => model.statisticViewModel.CountStudent)',
                '@Html.DisplayNameFor(model => model.statisticViewModel.CountEmployee)',
                '@Html.DisplayNameFor(model => model.statisticViewModel.CountStaff)',
                '@Html.DisplayNameFor(model => model.statisticViewModel.CountVisitor)',
            ],
            datasets: [{
                label: 'إحصائيات',
                backgroundColor: [
                    "rgba(255, 99, 132, 0.2)",
                    "rgba(255, 159, 64, 0.2)",
                ],
                borderWidth: 2,
                data: [
                    @Model.statisticViewModel.CountStudent,
                    @Model.statisticViewModel.CountEmployee,
                    @Model.statisticViewModel.CountStaff,
                    @Model.statisticViewModel.CountVisitor,
                    ]
            }]
        },
    });
</script>