EventSystem/Models/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EventSystem.Models
{
    public class Event
    {
        // from here ----
        //give the list of visitor, this relation we put it in any project
        public Event()
        {
            Visitors = new HashSet<Visitor>();
            //Date = "Time of day";
        }

        // c# model one to many
        public virtual ICollection<Visitor> Visitors { get; set; }
        //TO here ----

        public int EventID { get; set; }

        [Required(ErrorMessage = "{0} مطلوب.")]
        [Display(Name = "اسم الفعالية")]
        public string Name { get; set; }

        [Required(ErrorMessage = "{0} مطلوب.")]
        [Display(Name = "مكان الفعالية")]
        public string Place { get; set; }

        [Required(ErrorMessage = "{0} مطلوب.")]
        [Display(Name = "اليوم")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd hh:mm tt}", ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; }




    }
}

EventSystem/Models/Visitor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EventSystem.Models
{
    public class Visitor
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "{0} مطلوب.")]
        [Display(Name = "اسم الزائر")]
        public string VName { get; set; }

        [Required(ErrorMessage = "{0} مطلوب.")]
        [Display(Name = " البريد الالكتروني")]
        public string Email { get; set; }

        [Required(ErrorMessage = "{0} مطلوب.")]
        [Display(Name = " رقم الجوال")]
        public string PNumber { get; set; }

        [Required(ErrorMessage = "{0} مطلوب.")]
        [Display(Name = " العمر")]
        public int Age { get; set; }

        [Required(ErrorMessage = "{0} مطلوب.")]
        [Display(Name = " الجنس")]
        public string Gender { get; set; }

        [Required(ErrorMessage = "{0} مطلوب.")]
        [Display(Name = " الفئة")]
        public string Type { get; set; }
        // to make connication
        public Models.Event Event { get; set; }
        public int EventId { get; set; }
    }
}

EventSystem/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EventSystem.Models;

namespace EventSystem.Controllers
{
    [Authorize]
    public class EventsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Events
        public ActionResult Index()
        {
            return View(db.Events.ToList());
        }

        // GET: Events/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        //Add a method to but a visitor button in event page, its reseve an Event ID.
        public ActionResult Visitors(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // its a list a have to write a condition to cheack the id from the event in the prameter and make compere between the pram and id.
            // List<Visitor> visitors = db.Visitors.Where(a => a.EventId == id).ToList();
            
            // the "IEnumerable" is a type of list in the c#....
            IEnumerable<Visitor> visitors = db.Visitors.Where(a => a.EventId == id).AsEnumerable();
            if (visitors == null)
            {
                return HttpNotFound();
            }

            ViewBag.EventId = id;

            return View(visitors);
        }


        // GET: Events/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EventID,Name,Place,Date")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Events.Add(@event);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(@event);
        }

        // GET: Events/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EventID,Name,Place,Date")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@event).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(@event);
        }

        // GET: Events/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event @event = db.Events.Find(id);
            db.Events.Remove(@event);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EventSystem/Controllers/VisitorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EventSystem.Models;

namespace EventSystem.Controllers
{
    [Authorize]
    public class VisitorsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Visitors
        public ActionResult Index()
        {
            var visitors = db.Visitors.Include(v => v.Event);
            return View(visitors.ToList());
        }

        // GET: Visitors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visitor visitor = db.Visitors.Find(id);
            if (visitor == null)
            {
                return HttpNotFound();
            }
            return View(visitor);
        }

        // GET: Visitors/Create
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.EventId =id;
            return View();
        }

        // POST: Visitors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,VName,PNumber,Email,Age,Gender,Type,EventId")] Visitor visitor)
        {
            if (ModelState.IsValid)
            {
                db.Visitors.Add(visitor);
                db.SaveChanges();
                // To know where to go after create visitor. 
                return RedirectToAction("Details", "Events", new { id = visitor.EventId });
            }

            ViewBag.EventId = visitor.EventId;
            return View(visitor);
        }

        // GET: Visitors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visitor visitor = db.Visitors.Find(id);
            if (visitor == null)
            {
                return HttpNotFound();
            }
            ViewBag.EventId = new SelectList(db.Events, "EventID", "Name", visitor.EventId);
            return View(visitor);
        }

        // POST: Visitors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,VName,Email,Age,Gender,Type,EventId")] Visitor visitor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(visitor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EventId = new SelectList(db.Events, "EventID", "Name", visitor.EventId);
            return View(visitor);
        }

        // GET: Visitors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visitor visitor = db.Visitors.Find(id);
            if (visitor == null)
            {
                return HttpNotFound();
            }
            return View(visitor);
        }

        // POST: Visitors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Visitor visitor = db.Visitors.Find(id);
            db.Visitors.Remove(visitor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EventSystem/Views/Events/Create.cshtml
@model EventSystem.Models.Event

@*الي يطلع فوق بالتاب*@
@{
    ViewBag.Title = "اضافة فعالية";
}

<h2> الفعاليات</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title">اضافة فعالية</h3>
            <div class="box-tools pull-right">
                @*@Html.Partial("Partial/HeaderButtons")*@
            </div><!--box-tools pull-right-->
        </div><!-- /.box-header -->
        <div class="box-body">
            <div class=" col-lg-6">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br>

                <div class="form-group">
                    @Html.LabelFor(model => model.Place, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Place, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Place, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br>

                <div class="form-group">
                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", @id = "date-format" } })
                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br>

            </div>
        </div><!-- /.box-body -->
        <div class="box-footer">
            <div class=" col-lg-6">
                <div class="form-actions no-color">
                    <input type="submit" value="اضافة" class="btn btn-primary btn-xs" />
                    @Html.ActionLink("العودة الى قائمة الفعاليات", "Index", null, new { @class = "btn btn-default btn-xs" })
                </div>

            </div>
        </div>
    </div><!--box-->
}


@section Scripts {

    <link rel="stylesheet" href="~/Content/bootstrap-material-datetimepicker.css" />
    <link href="~/Content/icon.css" rel="stylesheet">

    <script type="text/javascript" src="~/Scripts/moment-with-locales.min.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap-material-datetimepicker.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#date-format').bootstrapMaterialDatePicker({
                format: 'HH:mm YYYY/MM/DD',
                weekStart: 0,
                cancelText: 'إلغاء',
                okText: 'موافق',
                minDate: new Date()
            });

            $.material.init()
        });
    </script>
    @Scripts.Render("~/bundles/jqueryval")
}

EventSystem/Views/Events/Delete.cshtml
@model EventSystem.Models.Event

@{
    ViewBag.Title = "حذف فعالية";
}


<h2>حذف الفعالية</h2>

<div>
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title">
                هل تريد حذف هذه الفعالية؟
            </h3>
        </div>
            <div class="box-body">
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane mt-30 active" id="overview">
                        <table class="table table-striped table-hover">
                            <tr>
                                <th> @Html.DisplayNameFor(model => model.Name)</th>
                                <td> @Html.DisplayFor(model => model.Name)</td>
                            </tr>
                            <tr>
                                <th> @Html.DisplayNameFor(model => model.Place)</th>
                                <td> @Html.DisplayFor(model => model.Place)</td>
                            </tr>
                            <tr>
                                <th> @Html.DisplayNameFor(model => model.Date.Date)</th>
                                <td> @Html.DisplayFor(model => model.Date.Date)</td>
                            </tr>
                            <tr>
                                <th> الوقت</th>
                                <td> @Html.DisplayFor(model => model.Date.TimeOfDay)</td>

                            </tr>
                        </table>
                    </div><!--tab overview profile-->

                </div><!--tab content-->

            </div><!--tab panel-->
            @*<button type="submit" class="btn btn-danger btn-xs"></button>*@
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="حذف" class="btn btn-danger btn-xs" /> 
                @Html.ActionLink("العودة الى القائمة", "Details", new { id = Model.EventID }, new { @class = "btn btn-default btn-xs" })
            </div>
            }
        </div><!-- /.box-body -->
    </div><!--box-tools pull-right-->
</div><!-- /.box-header -->

EventSystem/Views/Events/Details.cshtml
@model EventSystem.Models.Event

@{
    ViewBag.Title = "تفاصيل الفعالية";
}

<h2>الفعاليات</h2>



<div>
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title">
                تفاصيل الفعالية
            </h3>

            <div class="box-tools pull-right">
                @*the action name in the middale is comming from the Event controller from the method that i write*@

                @Html.ActionLink("الزائرين", "Visitors", new { id = Model.EventID }, new { @class = "btn btn-primary btn-xs" })
                @Html.ActionLink("اضافة زائر", "Create", "Visitors", new { id = Model.EventID }, new { @class = "btn btn-success btn-xs" })
                @Html.ActionLink("حذف", "Delete", new { id = Model.EventID }, new { @class = "btn btn-danger btn-xs" })
                @Html.ActionLink("تعديل", "Edit", new { id = Model.EventID }, new { @class = "btn btn-warning btn-xs" })
                @Html.ActionLink("العودة الى قائمة الفعاليات", "Index", null, new { @class = "btn btn-default btn-xs" })
            </div><!--box-tools pull-right-->
        </div><!-- /.box-header -->

        <div class="box-body">

            <div role="tabpanel">

                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active">
                        <a href="#overview" aria-controls="overview" role="tab" data-toggle="tab">
                            عام
                        </a>
                    </li>

                </ul>

                <div class="tab-content">

                    <div role="tabpanel" class="tab-pane mt-30 active" id="overview">

                        <table class="table table-striped table-hover">
                            <tr>
                                <th> @Html.DisplayNameFor(model => model.Name)</th>
                                <td> @Html.DisplayFor(model => model.Name)</td>
                            </tr>
                            <tr>
                                <th> @Html.DisplayNameFor(model => model.Place)</th>
                                <td> @Html.DisplayFor(model => model.Place)</td>
                            </tr>
                            <tr>
                                <th>التاريخ</th>
                                <td> @Model.Date.ToString("yyyy-MM-d")</td>
                            </tr>
                            <tr>
                                <th> الوقت</th>
                                <td> @Model.Date.ToString("hh:mm tt")</td>

                            </tr>
                        </table>
                    </div><!--tab overview profile-->

                </div><!--tab content-->

            </div><!--tab panel-->

        </div><!-- /.box-body -->
    </div><!--box-->
</div>

EventSystem/Views/Events/Edit.cshtml
@model EventSystem.Models.Event

@{
    ViewBag.Title = "تعديل بينات الفعالية";
}

<h2> الفعاليات</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title">تعديل معلومات الفعالية</h3>
            <div class="box-tools pull-right">
            </div><!--box-tools pull-right-->
        </div><!-- /.box-header -->
        <div class="box-body">
            <div class=" col-lg-6">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.EventID)

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br>

                <div class="form-group">
                    @Html.LabelFor(model => model.Place, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Place, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Place, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br>

                <div class="form-group">
                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @*value="@Model.Date" << to get the value *@
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", @id = "datepicker", @width = "276" } })
                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br>
            </div>
            </div><!-- /.box-body -->
            <div class="box-footer">
                <div class=" col-lg-6">
                    @* @Html.ActionLink("حفظ", "Save", null, new { @class = "btn btn-primary btn-xs" })*@
                    <input type="submit" value="حفظ" class="btn btn-primary btn-xs" />
                    @Html.ActionLink("العودة الى القائمة", "Details", new { id = Model.EventID }, new { @class = "btn btn-default btn-xs" })
                </div>
            </div>
        </div>
    <script>
        $('#datepicker').datetimepicker({
            //uiLibrary: 'bootstrap',
            //format: "yyyy-mm-ddThh:ii"
            footer: true, modal: true
        });
    </script>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EventSystem/Views/Events/Index.cshtml
@model IEnumerable<EventSystem.Models.Event>

@{
    ViewBag.Title = "الفعاليات";
}

<h2>الفعاليات </h2>
<style>
    .img_Custom {
        width: 10%;
    }
</style>


<div>
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title">
                قائمة الفعاليات
            </h3>

            <div class="box-tools pull-right">
                @Html.ActionLink("اضافة فعالية", "Create", null, new { @class = "btn btn-primary btn-xs" })

            </div><!--box-tools pull-right-->
        </div><!-- /.box-header -->

        <div class="box-body">
            <table id="example" class="table table-striped table-bordered display" style="width:100%">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Place)

                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Date)
                        </th>
                        <th>
                            التاريخ
                            @*@Html.DisplayNameFor(model => model.Date.Day)*@
                        </th>
                        <th>
                            الوقت
                        </th>
                        <th>
                            عدد المسجلين
                        </th>
                        <th>
                            الحالة
                        </th>
                        <th>
                            الاجراءات
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @* we use item rether then htkl displayfor to the date and time *@
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Place)
                            </td>
                            <td>
                                @item.Date.ToString("dddd", new System.Globalization.CultureInfo("ar-SA"))
                            </td>
                            <td>
                                @item.Date.ToString("yyyy-MM-d")
                            </td>
                            <td>
                                @item.Date.ToString("hh:mm tt")
                            </td>
                            <td>
                                @item.Visitors.Count()
                            </td>
                            @* we use DateTime.Now to copmere with todays date *@
                            <td>
                                @if (item.Date > DateTime.Now)
                                {
                                    <img src="~/Content/iconfinder_Ball Green_34555.png" class="img_Custom" />
                                }

                                else
                                {
                                    <img src="~/Content/iconfinder_Ball Red_34556.png" class="img_Custom" />
                                }
                            </td>
                            <td>
                                @* @Html.ActionLink("Edit", "Edit", new { id=item.EventID }) |*@
                                @Html.ActionLink("التفاصيل", "Details", new { id = item.EventID }, new { @class = "btn btn-info btn-xs" })
                                @* @Html.ActionLink("Delete", "Delete", new { id=item.EventID })*@
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="box-footer">
        </div>
    </div>
</div>

EventSystem/Views/Events/Visitors.cshtml
@model IEnumerable<EventSystem.Models.Visitor>


@{
    ViewBag.Title = "الزائرين";
}

<h2>الفعاليات</h2>


<div>
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title">
                قائمة الزائرين
            </h3>

        </div><!-- /.box-header -->

        <div class="box-body">
            <table id="example" class="table table-striped table-bordered display" style="width:100%">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.VName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Email)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Age)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Gender)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Type)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @* we use item rether then htkl displayfor to the date and time *@
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.VName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Age)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Gender)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Type)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="box-footer">
            @Html.ActionLink("العودة الى القائمة", "Details", new { id = ViewBag.EventId }, new { @class = "btn btn-default btn-xs pull-right" })
        </div>
    </div>
</div>